provider: qwen
timeout: 30
temperature: 0.7
stream: true

models:
  - name: qwen3-32B
    base_url: http://{LLM_PROVIDER_HOST}/v1
    api_key: token-qwen3
  - name: qwen3-14B
    base_url: http://{LLM_PROVIDER_HOST}/v1
    api_key: token-qwen3
