'''
Description: 服务错误码
Author: zyq
Date: 2025-09-19 09:30:16
LastEditors: zyq
LastEditTime: 2025-09-19 10:33:32
'''

# chat服务错误码
CHAT_SERVICE_ERRCODE_START = -1000
CHAT_SERVICE_INIT_ERROR = -1001
CHAT_SERVICE_ERRCODE_END = -1999

# document服务错误码
DOCUMENT_SERVICE_ERRCODE_START = -2000
DOCUMENT_SERVICE_PDF_BATCH_TASK_MANAGER_INIT_ERROR = -2001
DOCUMENT_SERVICE_CONVERT_TASK_MANAGER_INIT_ERROR = -2002
DOCUMENT_SERVICE_TEXT_EXTRACT_TASK_MANAGER_INIT_ERROR = -2003
DOCUMENT_SERVICE_SUBMIT_TASK_ERROR = -2004
DOCUMENT_SERVICE_INIT_ERROR = -2005
DOCUMENT_SERVICE_INVALID_TASK_TYPE_ERROR = -2006
DOCUMENT_SERVICE_ERRCODE_END = -2999

# retrieval服务错误码
RETRIEVAL_SERVICE_ERRCODE_START = -3000
RETRIEVAL_SERVICE_INIT_ERROR = -3001
RETRIEVAL_SERVICE_TASK_NOT_FOUND_ERROR = -3002
RETRIEVAL_SERVICE_INVALID_TASK_ID_ERROR = -3003
RETRIEVAL_SERVICE_ERRCODE_END = -3999

def get_service_error_message(code: int) -> str:
    """根据服务错误码获取描述信息"""
    error_messages = {
        DOCUMENT_SERVICE_PDF_BATCH_TASK_MANAGER_INIT_ERROR: "PDF批量任务管理器初始化失败",
        DOCUMENT_SERVICE_CONVERT_TASK_MANAGER_INIT_ERROR: "格式转换任务管理器初始化失败",
        DOCUMENT_SERVICE_TEXT_EXTRACT_TASK_MANAGER_INIT_ERROR: "文本提取任务管理器初始化失败",
        DOCUMENT_SERVICE_SUBMIT_TASK_ERROR: "提交任务失败",
        DOCUMENT_SERVICE_INIT_ERROR: "document服务初始化失败",
        DOCUMENT_SERVICE_INVALID_TASK_TYPE_ERROR: "无效的任务前缀格式",
        
        CHAT_SERVICE_INIT_ERROR: "chat服务初始化失败",
        
        RETRIEVAL_SERVICE_INIT_ERROR: "retrieval服务初始化失败",
        RETRIEVAL_SERVICE_TASK_NOT_FOUND_ERROR: "构建任务不存在",
        RETRIEVAL_SERVICE_INVALID_TASK_ID_ERROR: "任务ID格式错误",
    }
    return error_messages.get(code, "未知错误")
