'''
Description: 服务错误码
Author: zyq
Date: 2025-09-19 09:30:16
LastEditors: zyq
LastEditTime: 2025-12-03 17:15:21
'''

# chat服务错误码
CHAT_SERVICE_ERRCODE_START = -1000
CHAT_SERVICE_INIT_ERROR = -1001
CHAT_SERVICE_DIFY_UPLOAD_FILE_ERROR = -1002
CHAT_SERVICE_DIFY_CHAT_ERROR = -1003
CHAT_SERVICE_ADD_FEEDBACK_ERROR = -1004
CHAT_SERVICE_GET_FEEDBACK_ERROR = -1005
CHAT_SERVICE_ADD_SUGGESTED_QUESTION_ERROR = -1006
CHAT_SERVICE_GET_HISTORY_MESSAGE_ERROR = -1007
CHAT_SERVICE_GET_CONVERSATION_LIST_ERROR = -1008
CHAT_SERVICE_DELETE_CONVERSATION_ERROR = -1009
CHAT_SERVICE_RENAME_CONVERSATION_ERROR = -1010
CHAT_SERVICE_STOP_CHAT_TASK_ERROR = -1011
CHAT_SERVICE_GET_WORKFLOW_RUN_STATUS_ERROR = -1012
CHAT_SERVICE_STOP_WORKFLOW_TASK_ERROR = -1013
CHAT_SERVICE_UPLOAD_WORKFLOW_FILE_ERROR = -1014
CHAT_SERVICE_GET_WORKFLOW_LOGS_ERROR = -1015
CHAT_SERVICE_GET_APP_INFO_ERROR = -1016
CHAT_SERVICE_GET_APP_PARAMETERS_ERROR = -1017
CHAT_SERVICE_GET_APP_SITE_ERROR = -1018
CHAT_SERVICE_DIFY_WORKFLOW_ERROR = -1019
CHAT_SERVICE_COZE_UPLOAD_FILE_ERROR = -1020
CHAT_SERVICE_COZE_CHAT_ERROR = -1021
CHAT_SERVICE_ERRCODE_END = -1999

# document服务错误码
DOCUMENT_SERVICE_ERRCODE_START = -2000
DOCUMENT_SERVICE_PDF_BATCH_TASK_MANAGER_INIT_ERROR = -2001
DOCUMENT_SERVICE_CONVERT_TASK_MANAGER_INIT_ERROR = -2002
DOCUMENT_SERVICE_TEXT_EXTRACT_TASK_MANAGER_INIT_ERROR = -2003
DOCUMENT_SERVICE_SUBMIT_TASK_ERROR = -2004
DOCUMENT_SERVICE_INIT_ERROR = -2005
DOCUMENT_SERVICE_INVALID_TASK_TYPE_ERROR = -2006
DOCUMENT_SERVICE_ERRCODE_END = -2999

# retrieval服务错误码
RETRIEVAL_SERVICE_ERRCODE_START = -3000
RETRIEVAL_SERVICE_INIT_ERROR = -3001
RETRIEVAL_SERVICE_TASK_NOT_FOUND_ERROR = -3002
RETRIEVAL_SERVICE_INVALID_TASK_ID_ERROR = -3003
RETRIEVAL_SERVICE_PROVIDER_NOT_SUPPORTED = -3004
RETRIEVAL_SERVICE_CREDENTIAL_MISSING = -3005
RETRIEVAL_SERVICE_PROVIDER_CALL_FAILED = -3006
RETRIEVAL_SERVICE_INVALID_CREDENTIAL = -3007
RETRIEVAL_SERVICE_USER_CTX_MISSING = -3008
RETRIEVAL_SERVICE_ADD_OR_UPDATE_CREDENTIAL_ERROR = -3009
RETRIEVAL_SERVICE_MULTIPLE_DOC_FOUND = -3010
RETRIEVAL_SERVICE_DOC_NOT_FOUND = -3011
RETRIEVAL_SERVICE_ERRCODE_END = -3999

# mcp服务错误码
MCP_SERVICE_ERRCODE_START = -4000
MCP_SERVICE_INIT_ERROR = -4001
MCP_SERVICE_META_SYNC_ERROR = -4002
MCP_SERVICE_TOOL_NOT_FOUND = -4003
MCP_SERVICE_AGENT_MODE_NOT_ALLOWED = -4004
MCP_SERVICE_ERRCODE_END = -4999

def get_service_error_message(code: int) -> str:
    """根据服务错误码获取描述信息"""
    error_messages = {
        DOCUMENT_SERVICE_PDF_BATCH_TASK_MANAGER_INIT_ERROR: "PDF批量任务管理器初始化失败",
        DOCUMENT_SERVICE_CONVERT_TASK_MANAGER_INIT_ERROR: "格式转换任务管理器初始化失败",
        DOCUMENT_SERVICE_TEXT_EXTRACT_TASK_MANAGER_INIT_ERROR: "文本提取任务管理器初始化失败",
        DOCUMENT_SERVICE_SUBMIT_TASK_ERROR: "提交任务失败",
        DOCUMENT_SERVICE_INIT_ERROR: "document服务初始化失败",
        DOCUMENT_SERVICE_INVALID_TASK_TYPE_ERROR: "无效的任务前缀格式",
        
        CHAT_SERVICE_INIT_ERROR: "chat服务初始化失败",
        CHAT_SERVICE_DIFY_UPLOAD_FILE_ERROR: "Dify文件上传失败",
        CHAT_SERVICE_DIFY_CHAT_ERROR: "Dify对话流请求失败",
        CHAT_SERVICE_ADD_FEEDBACK_ERROR: "添加消息反馈失败",
        CHAT_SERVICE_GET_FEEDBACK_ERROR: "获取消息反馈失败",
        CHAT_SERVICE_ADD_SUGGESTED_QUESTION_ERROR: "添加建议问题失败",
        CHAT_SERVICE_GET_HISTORY_MESSAGE_ERROR: "获取历史消息失败",
        CHAT_SERVICE_GET_CONVERSATION_LIST_ERROR: "获取会话列表失败",
        CHAT_SERVICE_DELETE_CONVERSATION_ERROR: "删除会话失败",
        CHAT_SERVICE_RENAME_CONVERSATION_ERROR: "重命名会话失败",
        CHAT_SERVICE_STOP_CHAT_TASK_ERROR: "停止对话流任务失败",
        CHAT_SERVICE_GET_WORKFLOW_RUN_STATUS_ERROR: "获取workflow执行情况失败",
        CHAT_SERVICE_STOP_WORKFLOW_TASK_ERROR: "停止workflow任务失败",
        CHAT_SERVICE_UPLOAD_WORKFLOW_FILE_ERROR: "上传workflow文件失败",
        CHAT_SERVICE_GET_WORKFLOW_LOGS_ERROR: "获取workflow日志失败",
        CHAT_SERVICE_GET_APP_INFO_ERROR: "获取应用基本信息失败",
        CHAT_SERVICE_GET_APP_PARAMETERS_ERROR: "获取应用参数失败",
        CHAT_SERVICE_GET_APP_SITE_ERROR: "获取应用WebApp设置失败",
        CHAT_SERVICE_DIFY_WORKFLOW_ERROR: "Dify workflow请求失败",
        CHAT_SERVICE_COZE_UPLOAD_FILE_ERROR: "Coze文件上传失败",

        RETRIEVAL_SERVICE_INIT_ERROR: "retrieval服务初始化失败",
        RETRIEVAL_SERVICE_TASK_NOT_FOUND_ERROR: "构建任务不存在",
        RETRIEVAL_SERVICE_INVALID_TASK_ID_ERROR: "任务ID格式错误",
        RETRIEVAL_SERVICE_PROVIDER_NOT_SUPPORTED: "当前provider不支持该操作",
        RETRIEVAL_SERVICE_CREDENTIAL_MISSING: "缺少知识库访问凭证apikey",
        RETRIEVAL_SERVICE_PROVIDER_CALL_FAILED: "外部provider调用失败",
        RETRIEVAL_SERVICE_INVALID_CREDENTIAL: "凭证不存在或已删除",
        RETRIEVAL_SERVICE_USER_CTX_MISSING: "缺少用户上下文信息",
        RETRIEVAL_SERVICE_ADD_OR_UPDATE_CREDENTIAL_ERROR: "添加或更新知识库凭证失败",
        RETRIEVAL_SERVICE_MULTIPLE_DOC_FOUND: "存在多个重名文档",
        RETRIEVAL_SERVICE_DOC_NOT_FOUND: "文档不存在",

        MCP_SERVICE_INIT_ERROR: "mcp服务初始化失败",
        MCP_SERVICE_META_SYNC_ERROR: "同步工具元数据失败",
        MCP_SERVICE_TOOL_NOT_FOUND: "工具不存在或未注册",
        MCP_SERVICE_AGENT_MODE_NOT_ALLOWED: "编排模式不允许",
    }
    return error_messages.get(code, "未知错误")
